### PR TITLE
pull request 2

### PR DESCRIPTION
**Pull request by Genius398**
pull request 2

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
uhhhh why do you want to remove yourself lol

**Comment by Genius398** [comment]
> uhhhh why do you want to remove yourself lol

cause I'm useless here

**Comment by FunctionalMetatable** [comment]
> cause I'm useless here

make an idea (like adding reactions) on the main repo. just even one small thing counts as a contribution

**Comment by Genius398** [comment]
ohh

**Comment by Genius398** [comment]
ok. i dint know that

**Pull request closed without merging**
